---
version: 1
disable_existing_loggers: False
 
# Define format of output logs (named 'simple').
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
 
handlers:
 
    # # Create rotating file handler using 'simple' format.
    # file_handler:
    #     class: logging.handlers.RotatingFileHandler
    #     level: INFO
    #     formatter: simple
    #     filename: log/operations-audit-query-service.log
    #     maxBytes: 10485760 # 10MB
    #     backupCount: 5
    #     encoding: utf8

    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout
 
root:
 
    level: INFO
    handlers: [console]
    #handlers: [file_handler, console]